const START_DEFAULT_CONTENT_GET = 'START_DEFAULT_CONTENT_GET',
	SUCCESS_DEFAULT_GETCONTENT = 'SUCCESS_DEFAULT_GETCONTENT',
	FAIL_DEFAULT_CONTENT = 'FAIL_DEFAULT_CONTENT',
	DELETE_DATA = 'DELETE_DATA';

export { START_DEFAULT_CONTENT_GET, SUCCESS_DEFAULT_GETCONTENT, FAIL_DEFAULT_CONTENT, DELETE_DATA };
